@section('robotsAll', $entity->indexType !== 'custom' ? robots_all($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('robotsGoogle',  $entity->indexType !== 'custom' ? robots_google($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('robotsYandex',  $entity->indexType !== 'custom' ? robots_yandex($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('robotsBing',  $entity->indexType !== 'custom' ? robots_bing($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('robotsYahoo',  $entity->indexType !== 'custom' ? robots_yahoo($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('robotsDuck',  $entity->indexType !== 'custom' ? robots_duck($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('robotsBaidu',  $entity->indexType !== 'custom' ? robots_baidu($entity->indexType, $entity->index) : 'noindex, nofollow')
@section('documentState', $entity->indexType !== 'custom' ? $entity->document_state : 'static')
@section('metaTitle', $entity->indexType !== 'custom' ? meta_title($entity) : $entity->title)
@section('metaDescription', $entity->indexType !== 'custom' ? meta_description($entity) : null)
@section('metaKeywords', $entity->indexType !== 'custom' ? $entity->meta_keywords : null)
@section('parent', $entity->indexType !== 'custom' ? is_parent($entity) : null)

@section('paginationFirst', $entity->indexType !== 'custom' ? is_pagination($entity, 'first') : null)
@section('paginationLast', $entity->indexType !== 'custom' ? is_pagination($entity, 'last') : null)
@section('paginationNext', $entity->indexType !== 'custom' ? is_pagination($entity, 'next') : null)
@section('paginationPrev', $entity->indexType !== 'custom' ? is_pagination($entity, 'prev') : null)